import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "typeface-amaranth";
import "./globals.css";
import HeaderComponent from "@/components/header/main-header";
import FooterComponent from "@/components/footer/page";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans">
        <HeaderComponent />
        {children}

        <FooterComponent />
      </body>
    </html>
  );
}
